### ISSUE TITLE
Ranking in ENS-NDT 

### ISSUE THREAD

**Issue by abakoa** [mbuzdalov/non-dominated-sorting#4]

**Comment by danrodgar** [comment]
We believe that there is a problem assigning rankings in the ENS-NDT algorithm.

Using the data:
 https://github.com/Proteek/Best-Order-Sort/blob/master/cloud_10000_10_1.txt

For the first solution:
0.797576 0.852030 0.109279 0.938269 0.404565 0.356024 0.905465 0.107549 0.840786 0.148536

The ranking should be 1 but the result is 0 (starting at 0 index)

**Comment by mbuzdalov** [comment]
I've checked the most recent branch, and all algorithms, including several configurations of ENS-NDT, produced the expected ranking of 1.

Could you please tell me how exactly do you run the algorithm?

**Comment by mbuzdalov** [comment]
@abakoa @danrodgar could you please confirm that everything works on your side or provide the way to reproduce the problem?

**Comment by danrodgar** [comment]
Sorry for the late reply, we need to check our environment them. We haven't
managed to do so as yet.

Best regards
'

**Comment by danrodgar** [comment]
Please, close this issue as it was our environment

**Comment by mbuzdalov** [comment]
Okay, thank you!
